### ISSUE TITLE
Files without vritual machine

### ISSUE THREAD

**Issue by AdamVerner** [TrustworthyComputing/csaw_esc_2019#3]
Hey, could we just get the files that are inside the virtual, so we could run it on our own distros?

Thanks

**Comment by ptrick9** [comment]
The files that are in the 'Challenge Releases' folder are all that you will need for the challenges. If you don't want to use the provided VM, you will simply need to ensure that you have the installed the drivers for the Teensy 3.2 and AVRDude so that you can program the board. The included script should show you what you need installed.

**Comment by AdamVerner** [comment]
what about the `solver.py` which is showcased in the tutorial video?
I already downloaded it from the VM but I think the file should be included in the challenge set
